[build]
  publish = "."
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npx serve ."
  command = "npm run dev"
  port = 8888
  publish = "."
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-emails"
